### PR TITLE
Weather

### PR DESCRIPTION
**Pull request by gagc056**
This is the first pull request for the weather-app project

### CODE REVIEW

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED 

Hi, @gagc056 good job working on this, you made an elegant UI, and this project is almost done but for some little changes to be made.

User should be able to toggle between Celcius and Fahrenheit
see

Make changes to the background after every search
see

[OPTIONAL] Output a nice message when a location is not found, undefined is not so nice. :slightly_smiling_face: 

Please make changes and request for another review :+1: 
**RAPHAEL NORIODE** :mask:

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
Changes Required :muscle: 
Hi there @gagc056 
Great job implementing some of the requested changes. But there still somethings that we should improve.

- [ ] I know that was not said in the previous review, but your README file can benefit from some improvements. You can give a little bit more style to make the information more readable. Remember that this project is going to be part of your portfolio and hire managers are going to analyze your repositories. You can use this [template](https://github.com/microverseinc/readme-template).

- [ ] As it said in the requirement, there should be a switch (or something similar) to change the temperature between Celsius and Fahrenheit. The reason is that the requirements explicitly ask to do a new forecast request on the API server. Requirements prints [1](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/requests_requirement.png)       [2](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png)

Please kindly submit for code review again after making these changes.

Happy coding :computer: 
**Sergio Torres**

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Changes Required 🔍 

Hi @gagc056 👋 

Good job with changes. 💪 
However, I see a slight bug with your Celsius to Fahrenheit toggle... When I  back to celsius it changes to a value less accurate. One way yo can avoid this is by making a separate API call to get Fahrenheit which was suggested in the previous review or ensure your math logic is accurate.


See the progression of the bug here:
Screen Shot 2020-06-07 at 5 49 18 PM
Screen Shot 2020-06-07 at 5 49 26 PM
Screen Shot 2020-06-07 at 5 49 34 PM
Screen Shot 2020-06-07 at 5 49 40 PM
Screen Shot 2020-06-07 at 5 49 46 PM

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by mcrd25 — APPROVED** [review]
# Changes Approved and Apoligies ✔️ 

Hi @gagc056 👋 

Good job. I actually missed a requirement in that yo we're not supposed to use math as can be seen from this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/requests_requirement.png) from [Pathwright](https://microverse.pathwright.com/auth/sign-in/?next=/library/fast-track-curriculum/69047/path/step/59622133/). As it defeats the purpose of the exercise. So I'd suggest you do this before merging. But since I said it was ok to do Math I'd let you get the 👍 .

But please, do this before merging! 🙏 

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

**Pull request merged**
